name = "sentinel"
main = "src/index.ts"
compatibility_date = "2026-06-01"

[vars]
ENVIRONMENT = "production"

# Configuração do KV Namespace
[[kv_namespaces]]
binding = "SENTINEL_KV"
id = "4f9c55a833c14edaaf95bf2a9a647c02"

# Configuração do Banco de Dados D1
[[d1_databases]]
binding = "DB"
database_name = "sentineld1"
database_id = "a4ca7f95-c574-40f0-8061-5d6c2e5ea5e3"

# Configuração dos Durable Objects
[durable_objects]
bindings = [
  { name = "SentinelDO", class_name = "SentinelSessionDO" }
]

# Migrações necessárias para os Durable Objects
[[migrations]]
tag = "v1"
new_sqlite_classes = ["SentinelSessionDO"]
